channels:
- pytorch
- anaconda
- defaults
- conda-forge
dependencies:
- python=3.8
- 'pip>=21.0,<22'
- onnxruntime
- pytorch
- torchvision
- torchaudio
- cudatoolkit=11.1
- pip:
  - azureml-defaults
  - pandas
  - pytorch-lightning==1.4.2
  - jsonargparse[signatures]
  - inference-schema