# pytorch_lightning==1.7.2
seed_everything: true
trainer:
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      min_delta: 0.0001
      patience: 5
      verbose: True
      mode: min
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      monitor: val_acc
      dirpath: outputs/checkpoints
      filename: roshambo-{epoch:02d}-{val_acc:.2f}
      save_top_k: 3
      mode: min
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: 'step'
  default_root_dir: outputs
  auto_select_gpus: true
  gpus: 1
  max_epochs: 100
  logger: true
model:
  classes: 4
  lr: .01
data:
  data_dir: data/images
  batch_size: 32
  train_split: 0.8
