name: AzureML CLI Setup

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      group:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  azureml_cli_setup:
    name: AzureML CLI Setup
    runs-on: ubuntu-latest
    steps:
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.token }}

      - name: add az ml extension
        run: |
          az extension add -n ml -y

      - name: set azureml defaults
        run: |
            az config set defaults.workspace=${{ inputs.workspace }}
            az config set defaults.group=${{ inputs.group }}
