name: Deploy roshambo.ai

on:
  workflow_dispatch: 

  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'web/**'

env:
  NODE_VERSION: '16.x'
  APP_NAME: rocksie
  APP_RG: roshambo

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_TOKEN }}

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'create package'
      run: |
        # Build site and create artifact
        cd web
        yarn install
        yarn build
        zip -r ../webapp-deploy.zip *



    - name: 'Deploy to Azure WebApp'
      run: |
        # deploy using azure CLI
        az webapp deploy --resource-group ${{ env.APP_RG }} --name ${{ env.APP_NAME }} --src-path webapp-deploy.zip --type zip